server:
  port: 8124

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gd_blogs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: C:/Users/Administrator/Desktop/gd-blogs/blogs-backend/gdblogs/src/main/resources/images/

knife4j:
  enable: true
