spring:
  application:
      name: gdblogs
  datasource:
    url: jdbc:mysql://localhost:3306/gd_blogs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8124
#  http://localhost:8124/doc.html



# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.gdblogs.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false